name = "DigitalComm"
uuid = "a7b11256-881b-11e9-3aff-ff4a76f1bfae"
authors = ["Robin Gerzaguet <robin.gerzaguet@irisa.fr> and contributors"]
version = "1.1.1"

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DSP = "0.7"
FFTW = "1.4.5"
SpecialFunctions = "2.0"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"


[targets]
test = ["Test", "Documenter"]
